# permissions for end users to view coins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coin-viewer-role
rules:
- apiGroups:
  - crypto.kubetrail.io
  resources:
  - coins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crypto.kubetrail.io
  resources:
  - coins/status
  verbs:
  - get
