# permissions for end users to edit coins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coin-editor-role
rules:
- apiGroups:
  - crypto.kubetrail.io
  resources:
  - coins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crypto.kubetrail.io
  resources:
  - coins/status
  verbs:
  - get
