apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-operator-controller-manager
  namespace: crypto-operator-system
spec:
  template:
    spec:
      imagePullSecrets:
        - name: artifact-registry-key
